//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DevExpress.Xpo;

namespace MemberIdentification.DatabaseCode
{

    public partial class Persona : XPLiteObject
    {
        string fCity;
        [Size(255)]
        public string City
        {
            get { return this.fCity; }
            set { this.SetPropertyValue<string>("City", ref this.fCity, value); }
        }
        string fCompany;
        [Size(255)]
        public string Company
        {
            get { return this.fCompany; }
            set { this.SetPropertyValue<string>("Company", ref this.fCompany, value); }
        }
        int fId;
        [Key(true)]
        public int Id
        {
            get { return this.fId; }
            set { this.SetPropertyValue<int>("Id", ref this.fId, value); }
        }
        string fInitials;
        [Size(255)]
        public string Initials
        {
            get { return this.fInitials; }
            set { this.SetPropertyValue<string>("Initials", ref this.fInitials, value); }
        }
        string fOccupation;
        [Size(255)]
        public string Occupation
        {
            get { return this.fOccupation; }
            set { this.SetPropertyValue<string>("Occupation", ref this.fOccupation, value); }
        }
        string fTid;
        [Size(255)]
        public string Tid
        {
            get { return this.fTid; }
            set { this.SetPropertyValue<string>("Tid", ref this.fTid, value); }
        }
        int fSawTimes;
        public int SawTimes
        {
            get { return this.fSawTimes; }
            set { this.SetPropertyValue<int>("SawTimes", ref this.fSawTimes, value); }
        }
    }

}
